// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9DnZJJjlYxHiWA0hLl1Bwt5wWfrNtpc',
    appId: '1:224573018620:web:a0863ea86b03d6953f6279',
    messagingSenderId: '224573018620',
    projectId: 'workwise-ea1c2',
    authDomain: 'workwise-ea1c2.firebaseapp.com',
    storageBucket: 'workwise-ea1c2.firebasestorage.app',
    measurementId: 'G-G2BHNVW9M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHuhIYdQZcaJ7xhexDHAYp5DVCc4bJnQ',
    appId: '1:224573018620:android:9d3fd89e5eea95043f6279',
    messagingSenderId: '224573018620',
    projectId: 'workwise-ea1c2',
    storageBucket: 'workwise-ea1c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bsoIdSHxzaxK5PlnyUGeN9Hp3SEKu7A',
    appId: '1:224573018620:ios:f6e887f97d5ce7b23f6279',
    messagingSenderId: '224573018620',
    projectId: 'workwise-ea1c2',
    storageBucket: 'workwise-ea1c2.firebasestorage.app',
    iosBundleId: 'com.example.workWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bsoIdSHxzaxK5PlnyUGeN9Hp3SEKu7A',
    appId: '1:224573018620:ios:f6e887f97d5ce7b23f6279',
    messagingSenderId: '224573018620',
    projectId: 'workwise-ea1c2',
    storageBucket: 'workwise-ea1c2.firebasestorage.app',
    iosBundleId: 'com.example.workWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS9DnZJJjlYxHiWA0hLl1Bwt5wWfrNtpc',
    appId: '1:224573018620:web:0cbe2a6dff0c71353f6279',
    messagingSenderId: '224573018620',
    projectId: 'workwise-ea1c2',
    authDomain: 'workwise-ea1c2.firebaseapp.com',
    storageBucket: 'workwise-ea1c2.firebasestorage.app',
    measurementId: 'G-X5JHGMV967',
  );
}
